// <auto-generated />
using EF_Migration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFMigration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Migration.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "mathmatics",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "physics",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "chemistry",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Biology",
                            Price = 1660m
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "english",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("EF_Migration.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ahmed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ali"
                        },
                        new
                        {
                            Id = 3,
                            Name = "mohamed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "sara"
                        },
                        new
                        {
                            Id = 5,
                            Name = "george"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
